[workspace]
channels = ["conda-forge"]
platforms = ["linux-64", "osx-64", "osx-arm64", "win-64"]

[dependencies]  # should match docs/requirements.txt
jupyter = "*"
myst-parser = "*"
nbsphinx = "*"
notebook = "*"
pydata-sphinx-theme = "*"
sphinx = "*"
sphinx-copybutton = "*"

[pypi-dependencies]

[tasks]
docs = "./docs/make html"

[target.win-64.tasks]
docs = "./docs/make.bat html"

[environments]
default = ["default"]
