services:
  base:
    build:
      cache_from:
        - type=registry,ref=${NAMESPACE}here-be-dragons:buildcache-base${ARCH_SUFFIX:-}
      cache_to:
        - type=registry,ref=${NAMESPACE}here-be-dragons:buildcache-base${ARCH_SUFFIX:-},mode=max

  latest:
    build:
      cache_from:
        - type=registry,ref=${NAMESPACE}here-be-dragons:buildcache-latest${ARCH_SUFFIX:-}
      cache_to:
        - type=registry,ref=${NAMESPACE}here-be-dragons:buildcache-latest${ARCH_SUFFIX:-},mode=max

  next:
    build:
      cache_from:
        - type=registry,ref=${NAMESPACE}here-be-dragons:buildcache-next${ARCH_SUFFIX:-}
      cache_to:
        - type=registry,ref=${NAMESPACE}here-be-dragons:buildcache-next${ARCH_SUFFIX:-},mode=max
