services:
  base:
    image: ${NAMESPACE:-localhost/}here-be-dragons:base${ARCH_SUFFIX:-}
    build:
      args:
        - GEOS_VER=${GEOS_VER}
        - PARALLEL=${PARALLEL:-8}
        - PROJ_VER=${PROJ_VER}
        - NAMESPACE=${NAMESPACE:-localhost/}
      dockerfile: base.Dockerfile
    env_file:
      - "../versions.env"

  latest:
    image: ${NAMESPACE:-localhost/}here-be-dragons:latest${ARCH_SUFFIX:-}
    build:
      args:
        - BASE_IMAGE_TAG=base${ARCH_SUFFIX:-}
        - ARROW_VER=${ARROW_VER_LATEST}
        - GDAL_VER=${GDAL_VER_LATEST}
        - PARALLEL=${PARALLEL:-8}
        - PYTHON_VER=${PYTHON_VER_LATEST}
        - NAMESPACE=${NAMESPACE:-localhost/}
      dockerfile: build.Dockerfile
      tags:
        - ${NAMESPACE:-localhost/}here-be-dragons:latest${ARCH_SUFFIX:-}
        - ${NAMESPACE:-localhost/}here-be-dragons:stable${ARCH_SUFFIX:-}
        - ${NAMESPACE:-localhost/}here-be-dragons:py${LATEST_TAG}${ARCH_SUFFIX:-}
        - ${NAMESPACE:-localhost/}here-be-dragons:py${LATEST_TAG_SHORT}${ARCH_SUFFIX:-}
    env_file:
      - "../versions.env"

  next:
    image: ${NAMESPACE:-localhost/}here-be-dragons:next${ARCH_SUFFIX:-}
    build:
      args:
        - BASE_IMAGE_TAG=base${ARCH_SUFFIX:-}
        - ARROW_VER=${ARROW_VER_NEXT}
        - GDAL_VER=${GDAL_VER_NEXT}
        - PARALLEL=${PARALLEL:-8}
        - PYTHON_VER=${PYTHON_VER_NEXT}
        - NAMESPACE=${NAMESPACE:-localhost/}
      dockerfile: build.Dockerfile
      tags:
        - ${NAMESPACE:-localhost/}here-be-dragons:next${ARCH_SUFFIX:-}
        - ${NAMESPACE:-localhost/}here-be-dragons:experimental${ARCH_SUFFIX:-}
        - ${NAMESPACE:-localhost/}here-be-dragons:py${NEXT_TAG}${ARCH_SUFFIX:-}
        - ${NAMESPACE:-localhost/}here-be-dragons:py${NEXT_TAG_SHORT}${ARCH_SUFFIX:-}
    env_file:
      - "../versions.env"
