name: Bump Versions
on:
  workflow_dispatch:
  # schedule:
  #   - cron: '0 0 * * *'

jobs:
  update-versions:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v4

      - uses: prefix-dev/setup-pixi@v0.9.4
        with:
          pixi-version: v0.67.0
      - name: Update versions.toml
        run: |
          pixi run update --token ${{ secrets.GITHUB_TOKEN }}

      - name: Commit versions.toml
        run: |
          git add versions.toml
          if git diff-index --quiet HEAD; then
            echo "No changes to versions.toml. Skipping commit."
          else
            git config --local user.email "dev@corbelspatial.com"
            git config --local user.name "GitHub Actions"
            git commit -m "GitHub Action: Bump dependencies in versions.toml"
            git push
          fi